name: R-CMD-check

on: [push, pull_request]

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'devel'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel'}
          - {os: macOS-latest, r: 'release'}
          - {os: macOS-11, r: 'release', arch: 'arm64'}

    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}

    - name: Install Linux system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev
        sudo apt-get install -y libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libfontconfig1-dev
        sudo apt-get install -y libcurl4-gnutls-dev default-jdk
        sudo R CMD javareconf

    - name: Install rJava
      run: |
        Rscript -e "install.packages('rJava')"

    - name: Install other R dependencies
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_cran(c('qdapTools', 'gender', 'openNLP', 'RCurl', 'venneuler', 'qdap', 'ggwordcloud', 'ragg', 'ggmap', 'openNLPdata'))"

    - name: Check
      run: R CMD build . && R CMD check *tar.gz --as-cran

