name: R-CMD-check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
    - name: Check
      run: R CMD build . && R CMD check *tar.gz


